### ISSUE TITLE
Possibly Infected / Virus

### ISSUE THREAD

**Issue by okarpov** [direstraits96/BIOS-MOD-TOOLS#3]
the AMIBCP 5.02.0034.exe (and probably all other) seems infected:

https://www.virustotal.com/gui/file/7fe28fb8a7419c95fba428891e5b3914d9e2b365a5a8932da74db52a1c1dabd8

Be careful!

**Comment by Nable80** [comment]
Looks like a common false-positive, all major vendors marked this file as a safe one, and all 3 detections are too generic.

I still agree It's important to be careful with any executables and libraries from the Internet anyway. Don't forget to scan them after downloading and always use proper sandbox isolation tools.
